name: comment example
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: yasminsulthan/Github-_Actions_Demo2@v2.303.0
        with:
          type: create
          body: "- [ ] Run tests"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}
