 - name: Test create comment
   uses: ./
   id: couc
   with:
   issue-number: ${{ needs.build.outputs.issue-number }}
    body:|
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            reactions: '+1'
          

