name: commentexample
'on': push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "-[ ] Run tests"
          issue_number: '1'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: "- [x] Run tests"
          comment_id: ${{ steps.create.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete comment
        uses: jungwinter/comment@v1
        with:
          type: delete
          comment_id: ${{ steps.create.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
